-- ============================================================================
-- AgroAI Platform: Supabase PostgreSQL Database & Storage Schema
-- ============================================================================

-- 1. Create Scouting History Table (Farming scans, GPS, disease severities)
CREATE TABLE IF NOT EXISTS public.scouting_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    crop TEXT NOT NULL,
    disease TEXT NOT NULL,
    confidence NUMERIC(5, 2) NOT NULL,
    severity_percentage NUMERIC(5, 2) NOT NULL,
    severity_stage TEXT NOT NULL,
    pathogen_type TEXT NOT NULL,
    location TEXT DEFAULT 'Target Farm',
    image_url TEXT
);

-- 2. Create Farmer Validation Feedback Table (For active learning model retraining)
CREATE TABLE IF NOT EXISTS public.farmer_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_accurate BOOLEAN NOT NULL,
    corrected_crop TEXT,
    corrected_disease TEXT,
    comments TEXT
);

-- 3. Enable Row Level Security (RLS) & Public Access Policies
ALTER TABLE public.scouting_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.farmer_feedback ENABLE ROW LEVEL SECURITY;

-- Allow anonymous / service reads and writes
CREATE POLICY "Allow public read scouting_history" 
    ON public.scouting_history FOR SELECT USING (true);

CREATE POLICY "Allow public insert scouting_history" 
    ON public.scouting_history FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public delete scouting_history" 
    ON public.scouting_history FOR DELETE USING (true);

CREATE POLICY "Allow public read farmer_feedback" 
    ON public.farmer_feedback FOR SELECT USING (true);

CREATE POLICY "Allow public insert farmer_feedback" 
    ON public.farmer_feedback FOR INSERT WITH CHECK (true);

-- 4. Create Supabase Storage Bucket for Leaf Image Scans (Optional)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('crop-scans', 'crop-scans', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Access for crop-scans bucket" 
    ON storage.objects FOR SELECT 
    USING (bucket_id = 'crop-scans');

CREATE POLICY "Public Upload for crop-scans bucket" 
    ON storage.objects FOR INSERT 
    WITH CHECK (bucket_id = 'crop-scans');
